// 使用 provider 把 layout 包裹起來
// import { ApolloWrapper } from '/@lib/apollo-wrapper'
import { ApolloWrapper } from './lib/apollo-wrapper'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from './ui/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ApolloWrapper>
                    <Header />
                    {children}
                </ApolloWrapper>
            </body>
        </html>
    )
}
